#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
[[ "$(pwd)" =~ flash ]] && FLASH=true

function header() {
    echo -e "\033[01;31m"
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "==  ${1}  =="
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "\033[0m"
}

header "Resetting all conflicts"
git cf
echo
if [[ "$(git cf)" =~ ion.c ]]; then
    APPLY_ION=true
    git rf "drivers/staging/android/ion/ion.c"
fi

header "Applying all patches"
[[ -n ${APPLY_ION} ]] && git ap "${PATCHES_FOLDER}"/generic/ion.c.diff

header "Committing merge"
git fm || exit 1

header "Applying additional commits"
rm -f *.patch
cp "${PATCHES_FOLDER}"/generic/000*.patch .
sed -i "s/insert-commit-id-here/$(git log --format=%h -1 "$(git show -s --format=%P | awk '{print $2}')" drivers/staging/android/ion/ion.c)/g" 0002*.patch
git am *.patch || exit 1
rm -f *.patch
