#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
[[ "$(pwd)" =~ flash ]] && FLASH=true

function header() {
    echo -e "\033[01;31m"
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "==  ${1}  =="
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "\033[0m"
}

function die() {
    echo -e "\033[01;31m"
    echo "${@}"
    echo -e "\033[0m"
    exit 1
}

APPROVED_CONFLICTS=( "arch/arm64/kvm/hyp.S:1"
                     "fs/f2fs/checkpoint.c:12"
                     "fs/f2fs/data.c:6"
                     "fs/f2fs/dir.c:1"
                     "fs/f2fs/f2fs.h:10"
                     "fs/f2fs/file.c:3"
                     "fs/f2fs/inline.c:2"
                     "fs/f2fs/inode.c:6"
                     "fs/f2fs/node.c:7"
                     "fs/f2fs/node.h:1"
                     "fs/f2fs/recovery.c:8"
                     "fs/f2fs/segment.c:6"
                     "fs/f2fs/segment.h:7"
                     "fs/f2fs/super.c:9"
                     "fs/pstore/ram_core.c:1"
                     "include/linux/f2fs_fs.h:2" )
readarray -t CONFLICTS <<< "$(git cf)"
if [[ -n "${CONFLICTS[*]}" ]]; then
    header "Resetting all conflicts"
    for CONFLICT in "${CONFLICTS[@]}"; do
        FOUND=false
        for APPROVED_CONFLICT in "${APPROVED_CONFLICTS[@]}"; do
            ACTION=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 3)
            NOC=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 2)
            APPROVED_CONFLICT=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 1)
            [[ -z ${ACTION} ]] && ACTION=rf
            [[ ${CONFLICT} = ${APPROVED_CONFLICT} ]] && { FOUND=true; break; }
        done
        [[ ${NOC} -ne $(git lo HEAD..MERGE_HEAD "${CONFLICT}" | wc -l) ]] && die "${CONFLICT} resolution might be outdated!"
        if ${FOUND}; then
            case ${ACTION} in
                "rf") ACTION_STRING="Resetting" ;;
                "rm"*) ACTION_STRING="Removing" ;;
                *) die "Invalid action: ${ACTION}" ;;
            esac

            echo "${ACTION_STRING} ${CONFLICT}..."
            git "${ACTION}" "${CONFLICT}" &>/dev/null
        else
            die "${CONFLICT} not accounted for, bailing out!"
        fi
    done
    [[ -n "$(git cf)" ]] && die "Resetting conflicts failed!"
    [[ ${PWD} =~ op5 ]] && git rf fs/f2fs/file.c

    if [[ ${PWD} =~ wahoo ]]; then
        header "Applying all patches"
        git ap "${PATCHES_FOLDER}"/*.diff || exit 1
    fi

    header "Committing merge"
    git fm || exit 1
fi
