#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
[[ "$(pwd)" =~ flash ]] && FLASH=true

function header() {
    echo -e "\033[01;31m"
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "==  ${1}  =="
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "\033[0m"
}

header "Resetting all conflicts"
git cf
echo
git rf "arch/arm64/mm/init.c"
[[ -n ${FLASH} ]] && git rf "fs/fuse/dev.c"

header "Applying all patches"
git fp -1 --stdout 408a31cb69f01eaa25b38d68e1b854eadab9df00 | git ap -R || exit 1
git ap "${PATCHES_FOLDER}"/arm64-mm-check-for-upper-page_shift-bits-in-pfn_valid.patch || exit 1
if [[ -z $(git status --porcelain drivers/staging/android/ion/ion.c) ]]; then
    curl https://lore.kernel.org/lkml/20180831202738.78559-1-ghackmann@google.com/raw | git ap || exit 1
fi
if [[ -n ${FLASH} ]]; then
    git fp -1 --stdout a2477b0e67c52f4364a47c3ad70902bc2a61bd4c | git ap || exit 1
fi

header "Committing merge"
git fm || exit 1

header "Applying additional commits"
rm -f *.patch
cp "${PATCHES_FOLDER}"/000*.patch .
sed -i "s/insert-commit-id-here/$(git log --format=%h -1 "$(git show -s --format=%P | awk '{print $2}')" drivers/staging/android/ion/ion.c)/g" 0002*.patch
git am ${FLASH:+--exclude drivers/staging/android/ion/ion_priv.h} 0002*.patch || exit 1
rm -f *.patch
if [[ -n ${FLASH} ]]; then
    git ap "${PATCHES_FOLDER}"/flash/*.diff || exit 1
    git ca --no-edit || exit 1
fi
