#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
[[ "$(pwd)" =~ flash ]] && FLASH=true

function header() {
    echo -e "\033[01;31m"
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "==  ${1}  =="
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "\033[0m"
}

function die() {
    echo -e "\033[01;31m"
    echo "${@}"
    echo -e "\033[0m"
    exit 1
}

APPROVED_CONFLICTS=( "arch/arm64/Kconfig:1"
                     "arch/arm64/kernel/arm64ksyms.c:1"
                     "arch/arm64/kernel/asm-offsets.c:1"
                     "arch/arm64/kernel/vdso32/vdso.S:0"
                     "arch/arm64/kvm/hyp/fpsimd.S:0"
                     "drivers/firmware/psci.c:3"
                     "fs/dcache.c:1"
                     "include/linux/arm-smccc.h:8"
                     "include/linux/psci.h:2" )
readarray -t CONFLICTS <<< "$(git cf)"
if [[ -n "${CONFLICTS[*]}" ]]; then
    header "Resetting all conflicts"
    for CONFLICT in "${CONFLICTS[@]}"; do
        FOUND=false
        for APPROVED_CONFLICT in "${APPROVED_CONFLICTS[@]}"; do
            ACTION=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 3)
            NOC=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 2)
            APPROVED_CONFLICT=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 1)
            [[ -z ${ACTION} ]] && ACTION=rf
            [[ ${CONFLICT} = ${APPROVED_CONFLICT} ]] && { FOUND=true; break; }
        done
        [[ ${NOC} -ne $(git lo HEAD..MERGE_HEAD "${CONFLICT}" | wc -l) ]] && die "${CONFLICT} resolution might be outdated!"
        if ${FOUND}; then
            case ${ACTION} in
                "rf") ACTION_STRING="Resetting" ;;
                "rm"*) ACTION_STRING="Removing" ;;
                *) die "Invalid action: ${ACTION}" ;;
            esac

            echo "${ACTION_STRING} ${CONFLICT}..."
            git "${ACTION}" "${CONFLICT}" &>/dev/null
        else
            die "${CONFLICT} not accounted for, bailing out!"
        fi
    done
    [[ -n "$(git cf)" ]] && die "Resetting conflicts failed!"

    header "Applying all patches"
    git ch MERGE_HEAD -- include/linux/arm-smccc.h
    if ! grep -q d_instantiate_new fs/dcache.c; then
        git fp -1 --stdout a97cb8dfea412ac4d42e1abcf9ed4ab0f8ebcbb3 | git ap -R || exit ${?}
        git diff v4.4.199..MERGE_HEAD fs/dcache.c | git ap || exit ${?}
    fi
    [[ $(grep -c ARM_SMCCC arch/arm64/Kconfig) -gt 1 ]] && { git ap "${PATCHES_FOLDER}"/Kconfig.arm64.diff || exit ${?}; }
    git ap "${PATCHES_FOLDER}"/psci.diff || exit ${?}

    header "Committing merge"
    git fm || exit 1
fi
