#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
[[ "$(pwd)" =~ flash ]] && FLASH=true

function header() {
    echo -e "\033[01;31m"
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "==  ${1}  =="
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "\033[0m"
}

function die() {
    echo -e "\033[01;31m"
    echo "${@}"
    echo -e "\033[0m"
    exit 1
}

APPROVED_CONFLICTS=(
    "drivers/irqchip/irq-gic.c:1" # Adjust context for http://source.codeaurora.org/quic/la/kernel/msm-4.9/commit/?id=c63401efe50598c6f61bc4823844b94433bd8148
    "drivers/usb/host/xhci-plat.c:1" # Discard because we did not integrate the reverted commit in the first place
    "net/netlink/genetlink.c:1" # Work around http://source.codeaurora.org/quic/la/kernel/msm-4.9/commit/?id=50ed2064bf93568a61204c745ce5db17db68f48d
    "sound/core/compress_offload.c:1" # Discard and prefer https://source.codeaurora.org/quic/la/kernel/msm-4.9/commit/?id=fd4953947befce450ef488b93b052e63c636b060
)
readarray -t CONFLICTS <<< "$(git cf)"
if [[ -n "${CONFLICTS[*]}" ]]; then
    header "Resetting all conflicts"
    for CONFLICT in "${CONFLICTS[@]}"; do
        FOUND=false
        for APPROVED_CONFLICT in "${APPROVED_CONFLICTS[@]}"; do
            ACTION=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 3)
            NOC=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 2)
            APPROVED_CONFLICT=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 1)
            [[ -z ${ACTION} ]] && ACTION=rf
            [[ ${CONFLICT} = ${APPROVED_CONFLICT} ]] && { FOUND=true; break; }
        done
        [[ ${NOC} -ne $(git lo HEAD..MERGE_HEAD "${CONFLICT}" | wc -l) ]] && die "${CONFLICT} resolution might be outdated!"
        if ${FOUND}; then
            case ${ACTION} in
                "rf") ACTION_STRING="Resetting" ;;
                "rm"*) ACTION_STRING="Removing" ;;
                *) die "Invalid action: ${ACTION}" ;;
            esac

            echo "${ACTION_STRING} ${CONFLICT}..."
            git "${ACTION}" "${CONFLICT}" &>/dev/null
        else
            die "${CONFLICT} not accounted for, bailing out!"
        fi
    done
    [[ -n "$(git cf)" ]] && die "Resetting conflicts failed!"

    header "Applying all patches"
    git fp -1 --stdout 50ed2064bf93568a61204c745ce5db17db68f48d | git ap -R || exit ${?}
    git diff v4.9.230..MERGE_HEAD net/netlink/genetlink.c | git ap || exit ${?}
    git ap "${PATCHES_FOLDER}"/*.diff || exit ${?}

    header "Committing merge"
    git fm || exit 1
fi
