#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)

function header() {
    echo -e "\033[01;31m"
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "==  ${1}  =="
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "\033[0m"
}

header "Resetting all conflicts"
git cf
echo
git ra

header "Applying all patches"
git fp -1 --stdout 1c4a6945fde71d5a426ea8adab895643ff848c3f | git ap -R
git fp -1 --stdout c6a9c8e51b188d049496643db2cfbb67df65190c | git ap -R
git fp -1 --stdout 68709f45385aeddb0ca96a060c0c8259944f321b | git ap
git fp -1 --stdout 5ad356eabc47d26a92140a0c4b20eba471c10de3 | git ap

header "Committing merge"
git fm

header "Applying additional commits"
rm *.patch
cp "${PATCHES_FOLDER}"/000*.patch .
sed -i "s/insert-commit-id-here/$(git log --format=%h -1 "${1}" drivers/staging/android/ion/ion.c)/g" 0002*.patch
git am *.patch
rm *.patch
