#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
[[ "$(pwd)" =~ flash ]] && FLASH=true

function header() {
    echo -e "\033[01;31m"
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "==  ${1}  =="
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "\033[0m"
}

header "Resetting all conflicts"
git cf
echo
git rf "arch/arm64/mm/init.c"
[[ -n ${FLASH} ]] && git rf "fs/fuse/dev.c"

header "Applying all patches"
git fp -1 --stdout 1c4a6945fde71d5a426ea8adab895643ff848c3f | git ap -R || exit 1
git fp -1 --stdout c6a9c8e51b188d049496643db2cfbb67df65190c | git ap -R || exit 1
git fp -1 --stdout 68709f45385aeddb0ca96a060c0c8259944f321b | git ap || exit 1
git fp -1 --stdout 5ad356eabc47d26a92140a0c4b20eba471c10de3 | git ap || exit 1
if [[ -n ${FLASH} ]]; then
    for SHA in 87114373ea50 45ff350bbd9d b8f95e5d13f5 a2477b0e67c5; do
        git fp -1 --stdout ${SHA} | git ap --include fs/fuse/dev.c || exit 1
    done
fi

header "Committing merge"
git fm || exit 1
