#!/usr/bin/env bash

function header() {
    echo -e "\033[01;31m"
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "==  ${1}  =="
    echo -e "====$(for i in $(seq ${#1}); do echo -e "=\c"; done)===="
    echo -e "\033[0m"
}

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)

header "Applying fixup for ufshcd patch in 4.14.184"
git ap "${PATCHES_FOLDER}"/ufshcd.c.diff || exit ${?}
git cad --no-edit
